version: '3.9'
services:
  db:
    image: postgres:13.3
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user_quest
      POSTGRES_PASSWORD: password_quest1206
      POSTGRES_DB: database_quest

  server:
    build: server/
    command: python ./main.py
    ports:
       - "127.0.0.1:8000:8000"
    depends_on:
      - db
